name: Chromastage
options:
  bundleIdPrefix: com.chromastage
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "13.0"

targets:
  Chromastage:
    type: application
    platform: macOS
    sources:
      - path: Chromastage/Sources
      - path: Chromastage/Resources
        type: folder
    settings:
      base:
        INFOPLIST_FILE: Chromastage/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.chromastage.app
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
